server:
  port: 5408
  tomcat:
    uri-encoding: utf-8

spring:
  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    encoding: UTF-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master
      strict: false
      datasource:
        login:
          url: jdbc:mysql://localhost:3306/vhr_login?useUnicode=true&characterEncoding=utf8
          username: vhr_login
          password: JRwRdYYAAFT7mnGP
        master:
          url: jdbc:mysql://localhost:3306/vhr_master?useUnicode=true&characterEncoding=utf8
          username: vhr_master
          password: zyw4aMjzmAKNbeZd
    druid:
      stat-view-servlet:
        enabled: true
        login-username: WongHZ
        login-password: wzh19981014
      web-stat-filter:
        enabled: true
        exclusions:
          url-pattern: /druid/*
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
        max-active: 8

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

mybatis-plus:
  #配置 mybatis-plus.Login_Mapper-locations
  mapper-locations: classpath*:/mapper/**/*.xml
  #配置日志，可查看生成的sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

ignore:
  get:
    - "/loginpage"
    - "/static/**"
    - "/css/**"
    - "/js/**"
    - "/lib/**"
    - "/ueditor/**"
    - "/image/**"
    - "/druid/**"
  post:
    - "/login"


